#[cfg(feature="winapi_app")] #[repr(C)] pub struct WIN32_FILE_ATTRIBUTE_DATA { dwFileAttributes: ::minwindef::DWORD, ftCreationTime: ::minwindef::FILETIME, ftLastAccessTime: ::minwindef::FILETIME, ftLastWriteTime: ::minwindef::FILETIME, nFileSizeHigh: ::minwindef::DWORD, nFileSizeLow: ::minwindef::DWORD } /* fileapi.h:564:16, fileapi.h:564:16, fileapi.h:564:16 */
#[cfg(feature="winapi_app")] pub type LPWIN32_FILE_ATTRIBUTE_DATA = *mut ::fileapi::WIN32_FILE_ATTRIBUTE_DATA; /* fileapi.h:571:31, fileapi.h:571:31, fileapi.h:571:31 */
#[cfg(feature="winapi_desktop")] #[repr(C)] pub struct BY_HANDLE_FILE_INFORMATION { dwFileAttributes: ::minwindef::DWORD, ftCreationTime: ::minwindef::FILETIME, ftLastAccessTime: ::minwindef::FILETIME, ftLastWriteTime: ::minwindef::FILETIME, dwVolumeSerialNumber: ::minwindef::DWORD, nFileSizeHigh: ::minwindef::DWORD, nFileSizeLow: ::minwindef::DWORD, nNumberOfLinks: ::minwindef::DWORD, nFileIndexHigh: ::minwindef::DWORD, nFileIndexLow: ::minwindef::DWORD } /* fileapi.h:611:16, fileapi.h:611:16, fileapi.h:611:16 */
#[cfg(feature="winapi_desktop")] pub type PBY_HANDLE_FILE_INFORMATION = *mut ::fileapi::BY_HANDLE_FILE_INFORMATION; /* fileapi.h:622:32, fileapi.h:622:32, fileapi.h:622:32 */
#[cfg(feature="winapi_desktop")] pub type LPBY_HANDLE_FILE_INFORMATION = *mut ::fileapi::BY_HANDLE_FILE_INFORMATION; /* fileapi.h:622:62, fileapi.h:622:62, fileapi.h:622:62 */
#[cfg(feature="winapi_app")] #[cfg(any(feature="winapi_ver_06020000"))] #[repr(C)] pub struct CREATEFILE2_EXTENDED_PARAMETERS { dwSize: ::minwindef::DWORD, dwFileAttributes: ::minwindef::DWORD, dwFileFlags: ::minwindef::DWORD, dwSecurityQosFlags: ::minwindef::DWORD, lpSecurityAttributes: ::minwinbase::LPSECURITY_ATTRIBUTES, hTemplateFile: ::winnt::HANDLE } /* fileapi.h:1260:16, fileapi.h:1260:16, fileapi.h:1260:16 */
#[cfg(feature="winapi_app")] #[cfg(any(feature="winapi_ver_06020000"))] pub type PCREATEFILE2_EXTENDED_PARAMETERS = *mut ::fileapi::CREATEFILE2_EXTENDED_PARAMETERS; /* fileapi.h:1267:37, fileapi.h:1267:37, fileapi.h:1267:37 */
#[cfg(feature="winapi_app")] #[cfg(any(feature="winapi_ver_06020000"))] pub type LPCREATEFILE2_EXTENDED_PARAMETERS = *mut ::fileapi::CREATEFILE2_EXTENDED_PARAMETERS; /* fileapi.h:1267:72, fileapi.h:1267:72, fileapi.h:1267:72 */
#[cfg(feature="winapi_app")] pub const CREATE_NEW: i32 = 0x1i32; /* Integer(1, Yes, Unknown) */ /* fileapi.h:51:9, fileapi.h:51:9, fileapi.h:51:9 */
#[cfg(feature="winapi_app")] pub const CREATE_ALWAYS: i32 = 0x2i32; /* Integer(2, Yes, Unknown) */ /* fileapi.h:52:9, fileapi.h:52:9, fileapi.h:52:9 */
#[cfg(feature="winapi_app")] pub const OPEN_EXISTING: i32 = 0x3i32; /* Integer(3, Yes, Unknown) */ /* fileapi.h:53:9, fileapi.h:53:9, fileapi.h:53:9 */
#[cfg(feature="winapi_app")] pub const OPEN_ALWAYS: i32 = 0x4i32; /* Integer(4, Yes, Unknown) */ /* fileapi.h:54:9, fileapi.h:54:9, fileapi.h:54:9 */
#[cfg(feature="winapi_app")] pub const TRUNCATE_EXISTING: i32 = 0x5i32; /* Integer(5, Yes, Unknown) */ /* fileapi.h:55:9, fileapi.h:55:9, fileapi.h:55:9 */
