#[cfg(feature="winapi_desktop")] #[repr(C)] pub struct PROCESS_INFORMATION { hProcess: ::winnt::HANDLE, hThread: ::winnt::HANDLE, dwProcessId: ::minwindef::DWORD, dwThreadId: ::minwindef::DWORD } /* processthreadsapi.h:53:16, processthreadsapi.h:53:16, processthreadsapi.h:53:16 */
#[cfg(feature="winapi_desktop")] pub type PPROCESS_INFORMATION = *mut ::processthreadsapi::PROCESS_INFORMATION; /* processthreadsapi.h:58:25, processthreadsapi.h:58:25, processthreadsapi.h:58:25 */
#[cfg(feature="winapi_desktop")] pub type LPPROCESS_INFORMATION = *mut ::processthreadsapi::PROCESS_INFORMATION; /* processthreadsapi.h:58:48, processthreadsapi.h:58:48, processthreadsapi.h:58:48 */
#[cfg(feature="winapi_desktop")] #[repr(C)] pub struct STARTUPINFOA { cb: ::minwindef::DWORD, lpReserved: ::winnt::LPSTR, lpDesktop: ::winnt::LPSTR, lpTitle: ::winnt::LPSTR, dwX: ::minwindef::DWORD, dwY: ::minwindef::DWORD, dwXSize: ::minwindef::DWORD, dwYSize: ::minwindef::DWORD, dwXCountChars: ::minwindef::DWORD, dwYCountChars: ::minwindef::DWORD, dwFillAttribute: ::minwindef::DWORD, dwFlags: ::minwindef::DWORD, wShowWindow: ::minwindef::WORD, cbReserved2: ::minwindef::WORD, lpReserved2: ::minwindef::LPBYTE, hStdInput: ::winnt::HANDLE, hStdOutput: ::winnt::HANDLE, hStdError: ::winnt::HANDLE } /* processthreadsapi.h:60:16, processthreadsapi.h:60:16, processthreadsapi.h:60:16 */
#[cfg(feature="winapi_desktop")] pub type LPSTARTUPINFOA = *mut ::processthreadsapi::STARTUPINFOA; /* processthreadsapi.h:79:18, processthreadsapi.h:79:18, processthreadsapi.h:79:18 */
#[cfg(feature="winapi_desktop")] #[repr(C)] pub struct STARTUPINFOW { cb: ::minwindef::DWORD, lpReserved: ::winnt::LPWSTR, lpDesktop: ::winnt::LPWSTR, lpTitle: ::winnt::LPWSTR, dwX: ::minwindef::DWORD, dwY: ::minwindef::DWORD, dwXSize: ::minwindef::DWORD, dwYSize: ::minwindef::DWORD, dwXCountChars: ::minwindef::DWORD, dwYCountChars: ::minwindef::DWORD, dwFillAttribute: ::minwindef::DWORD, dwFlags: ::minwindef::DWORD, wShowWindow: ::minwindef::WORD, cbReserved2: ::minwindef::WORD, lpReserved2: ::minwindef::LPBYTE, hStdInput: ::winnt::HANDLE, hStdOutput: ::winnt::HANDLE, hStdError: ::winnt::HANDLE } /* processthreadsapi.h:80:16, processthreadsapi.h:80:16, processthreadsapi.h:80:16 */
#[cfg(feature="winapi_desktop")] pub type LPSTARTUPINFOW = *mut ::processthreadsapi::STARTUPINFOW; /* processthreadsapi.h:99:18, processthreadsapi.h:99:18, processthreadsapi.h:99:18 */
#[cfg(feature="winapi_desktop")] pub type STARTUPINFO = ::processthreadsapi::STARTUPINFOW; /* processthreadsapi.h:101:22, processthreadsapi.h:101:22, processthreadsapi.h:101:22 */
#[cfg(feature="winapi_desktop")] pub type LPSTARTUPINFO = ::processthreadsapi::LPSTARTUPINFOW; /* processthreadsapi.h:102:24, processthreadsapi.h:102:24, processthreadsapi.h:102:24 */
#[cfg(feature="winapi_desktop")] pub type PPROC_THREAD_ATTRIBUTE_LIST = *mut ::libc::c_void; /* processthreadsapi.h:711:45, processthreadsapi.h:711:45, processthreadsapi.h:711:45 */
#[cfg(feature="winapi_desktop")] pub type LPPROC_THREAD_ATTRIBUTE_LIST = *mut ::libc::c_void; /* processthreadsapi.h:711:75, processthreadsapi.h:711:75, processthreadsapi.h:711:75 */
#[cfg(feature="winapi_desktop")] #[repr(C)] pub enum THREAD_INFORMATION_CLASS {ThreadMemoryPriority = 0, ThreadAbsoluteCpuPriority = 1, ThreadInformationClassMax = 2} pub use self::THREAD_INFORMATION_CLASS::{ThreadMemoryPriority, ThreadAbsoluteCpuPriority, ThreadInformationClassMax}; /* processthreadsapi.h:1107:14, processthreadsapi.h:1107:14, processthreadsapi.h:1107:14 */
#[cfg(feature="winapi_desktop")] #[cfg(any(feature="winapi_ver_06020000"))] #[repr(C)] pub struct MEMORY_PRIORITY_INFORMATION { MemoryPriority: ::minwindef::ULONG } /* processthreadsapi.h:1149:16, processthreadsapi.h:1149:16, processthreadsapi.h:1149:16 */
#[cfg(feature="winapi_desktop")] #[cfg(any(feature="winapi_ver_06020000"))] pub type PMEMORY_PRIORITY_INFORMATION = *mut ::processthreadsapi::MEMORY_PRIORITY_INFORMATION; /* processthreadsapi.h:1151:33, processthreadsapi.h:1151:33, processthreadsapi.h:1151:33 */
#[cfg(feature="winapi_desktop")] #[cfg(any(feature="winapi_ver_06000000"))] pub const PROCESS_AFFINITY_ENABLE_AUTO_UPDATE: u64 = 0x1u64; /* Integer(1, No, Long) */ /* processthreadsapi.h:766:9, processthreadsapi.h:766:9, processthreadsapi.h:766:9 */
#[cfg(feature="winapi_desktop")] #[cfg(any(feature="winapi_ver_06000000"))] pub const PROC_THREAD_ATTRIBUTE_REPLACE_VALUE: i32 = 0x1i32; /* Integer(1, Yes, Unknown) */ /* processthreadsapi.h:786:9, processthreadsapi.h:786:9, processthreadsapi.h:786:9 */
#[cfg(feature="winapi_desktop")] #[cfg(any(feature="winapi_ver_06020000"))] pub const MEMORY_PRIORITY_LOWEST: i32 = 0x0i32; /* Integer(0, Yes, Unknown) */ /* processthreadsapi.h:1142:9, processthreadsapi.h:1142:9, processthreadsapi.h:1142:9 */
#[cfg(feature="winapi_desktop")] #[cfg(any(feature="winapi_ver_06020000"))] pub const MEMORY_PRIORITY_VERY_LOW: i32 = 0x1i32; /* Integer(1, Yes, Unknown) */ /* processthreadsapi.h:1143:9, processthreadsapi.h:1143:9, processthreadsapi.h:1143:9 */
#[cfg(feature="winapi_desktop")] #[cfg(any(feature="winapi_ver_06020000"))] pub const MEMORY_PRIORITY_LOW: i32 = 0x2i32; /* Integer(2, Yes, Unknown) */ /* processthreadsapi.h:1144:9, processthreadsapi.h:1144:9, processthreadsapi.h:1144:9 */
#[cfg(feature="winapi_desktop")] #[cfg(any(feature="winapi_ver_06020000"))] pub const MEMORY_PRIORITY_MEDIUM: i32 = 0x3i32; /* Integer(3, Yes, Unknown) */ /* processthreadsapi.h:1145:9, processthreadsapi.h:1145:9, processthreadsapi.h:1145:9 */
#[cfg(feature="winapi_desktop")] #[cfg(any(feature="winapi_ver_06020000"))] pub const MEMORY_PRIORITY_BELOW_NORMAL: i32 = 0x4i32; /* Integer(4, Yes, Unknown) */ /* processthreadsapi.h:1146:9, processthreadsapi.h:1146:9, processthreadsapi.h:1146:9 */
#[cfg(feature="winapi_desktop")] #[cfg(any(feature="winapi_ver_06020000"))] pub const MEMORY_PRIORITY_NORMAL: i32 = 0x5i32; /* Integer(5, Yes, Unknown) */ /* processthreadsapi.h:1147:9, processthreadsapi.h:1147:9, processthreadsapi.h:1147:9 */
