
extern "system" {
    pub static ALL_POWERSCHEMES_GUID: ::guiddef::GUID; /* winnt.h:12833:1 */
    pub static GUID_ACDC_POWER_SOURCE: ::guiddef::GUID; /* winnt.h:13700:1 */
    pub static GUID_ACTIVE_POWERSCHEME: ::guiddef::GUID; /* winnt.h:12879:1 */
    pub static GUID_ADAPTIVE_POWER_BEHAVIOR_SUBGROUP: ::guiddef::GUID; /* winnt.h:13024:1 */
    pub static GUID_ALLOW_AWAYMODE: ::guiddef::GUID; /* winnt.h:13132:1 */
    pub static GUID_ALLOW_DISPLAY_REQUIRED: ::guiddef::GUID; /* winnt.h:13009:1 */
    pub static GUID_ALLOW_RTC_WAKE: ::guiddef::GUID; /* winnt.h:13160:1 */
    pub static GUID_ALLOW_STANDBY_STATES: ::guiddef::GUID; /* winnt.h:13153:1 */
    pub static GUID_ALLOW_SYSTEM_REQUIRED: ::guiddef::GUID; /* winnt.h:13168:1 */
    pub static GUID_APPLAUNCH_BUTTON: ::guiddef::GUID; /* winnt.h:13783:1 */
    pub static GUID_AUDIO_PLAYBACK: ::guiddef::GUID; /* winnt.h:13145:1 */
    pub static GUID_BACKGROUND_TASK_NOTIFICATION: ::guiddef::GUID; /* winnt.h:13775:1 */
    pub static GUID_BATTERY_DISCHARGE_ACTION_0: ::guiddef::GUID; /* winnt.h:13237:1 */
    pub static GUID_BATTERY_DISCHARGE_ACTION_1: ::guiddef::GUID; /* winnt.h:13241:1 */
    pub static GUID_BATTERY_DISCHARGE_ACTION_2: ::guiddef::GUID; /* winnt.h:13245:1 */
    pub static GUID_BATTERY_DISCHARGE_ACTION_3: ::guiddef::GUID; /* winnt.h:13249:1 */
    pub static GUID_BATTERY_DISCHARGE_FLAGS_0: ::guiddef::GUID; /* winnt.h:13239:1 */
    pub static GUID_BATTERY_DISCHARGE_FLAGS_1: ::guiddef::GUID; /* winnt.h:13243:1 */
    pub static GUID_BATTERY_DISCHARGE_FLAGS_2: ::guiddef::GUID; /* winnt.h:13247:1 */
    pub static GUID_BATTERY_DISCHARGE_FLAGS_3: ::guiddef::GUID; /* winnt.h:13251:1 */
    pub static GUID_BATTERY_DISCHARGE_LEVEL_0: ::guiddef::GUID; /* winnt.h:13238:1 */
    pub static GUID_BATTERY_DISCHARGE_LEVEL_1: ::guiddef::GUID; /* winnt.h:13242:1 */
    pub static GUID_BATTERY_DISCHARGE_LEVEL_2: ::guiddef::GUID; /* winnt.h:13246:1 */
    pub static GUID_BATTERY_DISCHARGE_LEVEL_3: ::guiddef::GUID; /* winnt.h:13250:1 */
    pub static GUID_BATTERY_PERCENTAGE_REMAINING: ::guiddef::GUID; /* winnt.h:13733:1 */
    pub static GUID_BATTERY_SUBGROUP: ::guiddef::GUID; /* winnt.h:13225:1 */
    pub static GUID_CONSOLE_DISPLAY_STATE: ::guiddef::GUID; /* winnt.h:13001:1 */
    pub static GUID_CRITICAL_POWER_TRANSITION: ::guiddef::GUID; /* winnt.h:13120:1 */
    pub static GUID_CS_BATTERY_SAVER_ACTION: ::guiddef::GUID; /* winnt.h:13254:1 */
    pub static GUID_CS_BATTERY_SAVER_THRESHOLD: ::guiddef::GUID; /* winnt.h:13253:1 */
    pub static GUID_CS_BATTERY_SAVER_TIMEOUT: ::guiddef::GUID; /* winnt.h:13255:1 */
    pub static GUID_DEVICE_IDLE_POLICY: ::guiddef::GUID; /* winnt.h:13679:1 */
    pub static GUID_DEVICE_POWER_POLICY_VIDEO_BRIGHTNESS: ::guiddef::GUID; /* winnt.h:12977:1 */
    pub static GUID_DEVICE_POWER_POLICY_VIDEO_DIM_BRIGHTNESS: ::guiddef::GUID; /* winnt.h:12983:1 */
    pub static GUID_DISK_ADAPTIVE_POWERDOWN: ::guiddef::GUID; /* winnt.h:13067:1 */
    pub static GUID_DISK_BURST_IGNORE_THRESHOLD: ::guiddef::GUID; /* winnt.h:13061:1 */
    pub static GUID_DISK_COALESCING_POWERDOWN_TIMEOUT: ::guiddef::GUID; /* winnt.h:12914:1 */
    pub static GUID_DISK_IDLE_TIMEOUT: ::guiddef::GUID; /* winnt.h:13052:1 */
    pub static GUID_DISK_POWERDOWN_TIMEOUT: ::guiddef::GUID; /* winnt.h:13045:1 */
    pub static GUID_DISK_SUBGROUP: ::guiddef::GUID; /* winnt.h:13039:1 */
    pub static GUID_ENABLE_SWITCH_FORCED_SHUTDOWN: ::guiddef::GUID; /* winnt.h:13812:1 */
    pub static GUID_EXECUTION_REQUIRED_REQUEST_TIMEOUT: ::guiddef::GUID; /* winnt.h:12927:1 */
    pub static GUID_GLOBAL_USER_PRESENCE: ::guiddef::GUID; /* winnt.h:13740:1 */
    pub static GUID_HIBERNATE_FASTS4_POLICY: ::guiddef::GUID; /* winnt.h:13111:1 */
    pub static GUID_HIBERNATE_TIMEOUT: ::guiddef::GUID; /* winnt.h:13105:1 */
    pub static GUID_IDLE_BACKGROUND_TASK: ::guiddef::GUID; /* winnt.h:13768:1 */
    pub static GUID_IDLE_RESILIENCY_PERIOD: ::guiddef::GUID; /* winnt.h:12900:1 */
    pub static GUID_IDLE_RESILIENCY_PLATFORM_STATE: ::guiddef::GUID; /* winnt.h:12907:1 */
    pub static GUID_IDLE_RESILIENCY_SUBGROUP: ::guiddef::GUID; /* winnt.h:12894:1 */
    pub static GUID_INTSTEER_LOAD_PER_PROC_TRIGGER: ::guiddef::GUID; /* winnt.h:13827:1 */
    pub static GUID_INTSTEER_MODE: ::guiddef::GUID; /* winnt.h:13823:1 */
    pub static GUID_INTSTEER_SUBGROUP: ::guiddef::GUID; /* winnt.h:13819:1 */
    pub static GUID_INTSTEER_TIME_UNPARK_TRIGGER: ::guiddef::GUID; /* winnt.h:13831:1 */
    pub static GUID_LIDCLOSE_ACTION: ::guiddef::GUID; /* winnt.h:13215:1 */
    pub static GUID_LIDOPEN_POWERSTATE: ::guiddef::GUID; /* winnt.h:13216:1 */
    pub static GUID_LIDSWITCH_STATE_CHANGE: ::guiddef::GUID; /* winnt.h:13716:1 */
    pub static GUID_LOCK_CONSOLE_ON_WAKE: ::guiddef::GUID; /* winnt.h:13669:1 */
    pub static GUID_MAX_POWER_SAVINGS: ::guiddef::GUID; /* winnt.h:12803:1 */
    pub static GUID_MIN_POWER_SAVINGS: ::guiddef::GUID; /* winnt.h:12810:1 */
    pub static GUID_MONITOR_POWER_ON: ::guiddef::GUID; /* winnt.h:12972:1 */
    pub static GUID_NON_ADAPTIVE_INPUT_TIMEOUT: ::guiddef::GUID; /* winnt.h:13031:1 */
    pub static GUID_PCIEXPRESS_ASPM_POLICY: ::guiddef::GUID; /* winnt.h:13800:1 */
    pub static GUID_PCIEXPRESS_SETTINGS_SUBGROUP: ::guiddef::GUID; /* winnt.h:13794:1 */
    pub static GUID_POWERBUTTON_ACTION: ::guiddef::GUID; /* winnt.h:13196:1 */
    pub static GUID_POWERSCHEME_PERSONALITY: ::guiddef::GUID; /* winnt.h:12870:1 */
    pub static GUID_PROCESSOR_ALLOW_THROTTLING: ::guiddef::GUID; /* winnt.h:13302:1 */
    pub static GUID_PROCESSOR_CORE_PARKING_AFFINITY_HISTORY_DECREASE_FACTOR: ::guiddef::GUID; /* winnt.h:13519:1 */
    pub static GUID_PROCESSOR_CORE_PARKING_AFFINITY_HISTORY_THRESHOLD: ::guiddef::GUID; /* winnt.h:13526:1 */
    pub static GUID_PROCESSOR_CORE_PARKING_AFFINITY_WEIGHTING: ::guiddef::GUID; /* winnt.h:13533:1 */
    pub static GUID_PROCESSOR_CORE_PARKING_DECREASE_POLICY: ::guiddef::GUID; /* winnt.h:13484:1 */
    pub static GUID_PROCESSOR_CORE_PARKING_DECREASE_THRESHOLD: ::guiddef::GUID; /* winnt.h:13464:1 */
    pub static GUID_PROCESSOR_CORE_PARKING_DECREASE_TIME: ::guiddef::GUID; /* winnt.h:13512:1 */
    pub static GUID_PROCESSOR_CORE_PARKING_INCREASE_POLICY: ::guiddef::GUID; /* winnt.h:13471:1 */
    pub static GUID_PROCESSOR_CORE_PARKING_INCREASE_THRESHOLD: ::guiddef::GUID; /* winnt.h:13457:1 */
    pub static GUID_PROCESSOR_CORE_PARKING_INCREASE_TIME: ::guiddef::GUID; /* winnt.h:13505:1 */
    pub static GUID_PROCESSOR_CORE_PARKING_MAX_CORES: ::guiddef::GUID; /* winnt.h:13491:1 */
    pub static GUID_PROCESSOR_CORE_PARKING_MIN_CORES: ::guiddef::GUID; /* winnt.h:13498:1 */
    pub static GUID_PROCESSOR_CORE_PARKING_OVER_UTILIZATION_HISTORY_DECREASE_FACTOR: ::guiddef::GUID; /* winnt.h:13540:1 */
    pub static GUID_PROCESSOR_CORE_PARKING_OVER_UTILIZATION_HISTORY_THRESHOLD: ::guiddef::GUID; /* winnt.h:13547:1 */
    pub static GUID_PROCESSOR_CORE_PARKING_OVER_UTILIZATION_THRESHOLD: ::guiddef::GUID; /* winnt.h:13561:1 */
    pub static GUID_PROCESSOR_CORE_PARKING_OVER_UTILIZATION_WEIGHTING: ::guiddef::GUID; /* winnt.h:13554:1 */
    pub static GUID_PROCESSOR_DISTRIBUTE_UTILITY: ::guiddef::GUID; /* winnt.h:13651:1 */
    pub static GUID_PROCESSOR_IDLESTATE_POLICY: ::guiddef::GUID; /* winnt.h:13308:1 */
    pub static GUID_PROCESSOR_IDLE_ALLOW_SCALING: ::guiddef::GUID; /* winnt.h:13408:1 */
    pub static GUID_PROCESSOR_IDLE_DEMOTE_THRESHOLD: ::guiddef::GUID; /* winnt.h:13442:1 */
    pub static GUID_PROCESSOR_IDLE_DISABLE: ::guiddef::GUID; /* winnt.h:13415:1 */
    pub static GUID_PROCESSOR_IDLE_PROMOTE_THRESHOLD: ::guiddef::GUID; /* winnt.h:13450:1 */
    pub static GUID_PROCESSOR_IDLE_STATE_MAXIMUM: ::guiddef::GUID; /* winnt.h:13424:1 */
    pub static GUID_PROCESSOR_IDLE_TIME_CHECK: ::guiddef::GUID; /* winnt.h:13433:1 */
    pub static GUID_PROCESSOR_PARKING_CONCURRENCY_THRESHOLD: ::guiddef::GUID; /* winnt.h:13585:1 */
    pub static GUID_PROCESSOR_PARKING_CORE_OVERRIDE: ::guiddef::GUID; /* winnt.h:13569:1 */
    pub static GUID_PROCESSOR_PARKING_HEADROOM_THRESHOLD: ::guiddef::GUID; /* winnt.h:13593:1 */
    pub static GUID_PROCESSOR_PARKING_PERF_STATE: ::guiddef::GUID; /* winnt.h:13577:1 */
    pub static GUID_PROCESSOR_PERFSTATE_POLICY: ::guiddef::GUID; /* winnt.h:13314:1 */
    pub static GUID_PROCESSOR_PERF_BOOST_MODE: ::guiddef::GUID; /* winnt.h:13392:1 */
    pub static GUID_PROCESSOR_PERF_BOOST_POLICY: ::guiddef::GUID; /* winnt.h:13380:1 */
    pub static GUID_PROCESSOR_PERF_CORE_PARKING_HISTORY: ::guiddef::GUID; /* winnt.h:13626:1 */
    pub static GUID_PROCESSOR_PERF_DECREASE_HISTORY: ::guiddef::GUID; /* winnt.h:13618:1 */
    pub static GUID_PROCESSOR_PERF_DECREASE_POLICY: ::guiddef::GUID; /* winnt.h:13346:1 */
    pub static GUID_PROCESSOR_PERF_DECREASE_THRESHOLD: ::guiddef::GUID; /* winnt.h:13330:1 */
    pub static GUID_PROCESSOR_PERF_DECREASE_TIME: ::guiddef::GUID; /* winnt.h:13364:1 */
    pub static GUID_PROCESSOR_PERF_HISTORY: ::guiddef::GUID; /* winnt.h:13602:1 */
    pub static GUID_PROCESSOR_PERF_INCREASE_HISTORY: ::guiddef::GUID; /* winnt.h:13610:1 */
    pub static GUID_PROCESSOR_PERF_INCREASE_POLICY: ::guiddef::GUID; /* winnt.h:13338:1 */
    pub static GUID_PROCESSOR_PERF_INCREASE_THRESHOLD: ::guiddef::GUID; /* winnt.h:13322:1 */
    pub static GUID_PROCESSOR_PERF_INCREASE_TIME: ::guiddef::GUID; /* winnt.h:13355:1 */
    pub static GUID_PROCESSOR_PERF_LATENCY_HINT: ::guiddef::GUID; /* winnt.h:13636:1 */
    pub static GUID_PROCESSOR_PERF_LATENCY_HINT_PERF: ::guiddef::GUID; /* winnt.h:13643:1 */
    pub static GUID_PROCESSOR_PERF_TIME_CHECK: ::guiddef::GUID; /* winnt.h:13372:1 */
    pub static GUID_PROCESSOR_SETTINGS_SUBGROUP: ::guiddef::GUID; /* winnt.h:13264:1 */
    pub static GUID_PROCESSOR_THROTTLE_MAXIMUM: ::guiddef::GUID; /* winnt.h:13286:1 */
    pub static GUID_PROCESSOR_THROTTLE_MINIMUM: ::guiddef::GUID; /* winnt.h:13294:1 */
    pub static GUID_PROCESSOR_THROTTLE_POLICY: ::guiddef::GUID; /* winnt.h:13270:1 */
    pub static GUID_SESSION_DISPLAY_STATUS: ::guiddef::GUID; /* winnt.h:13751:1 */
    pub static GUID_SESSION_USER_PRESENCE: ::guiddef::GUID; /* winnt.h:13761:1 */
    pub static GUID_SLEEPBUTTON_ACTION: ::guiddef::GUID; /* winnt.h:13202:1 */
    pub static GUID_SLEEP_IDLE_THRESHOLD: ::guiddef::GUID; /* winnt.h:13084:1 */
    pub static GUID_SLEEP_SUBGROUP: ::guiddef::GUID; /* winnt.h:13076:1 */
    pub static GUID_STANDBY_TIMEOUT: ::guiddef::GUID; /* winnt.h:13090:1 */
    pub static GUID_SYSTEM_AWAYMODE: ::guiddef::GUID; /* winnt.h:13126:1 */
    pub static GUID_SYSTEM_BUTTON_SUBGROUP: ::guiddef::GUID; /* winnt.h:13177:1 */
    pub static GUID_SYSTEM_COOLING_POLICY: ::guiddef::GUID; /* winnt.h:13659:1 */
    pub static GUID_TYPICAL_POWER_SAVINGS: ::guiddef::GUID; /* winnt.h:12817:1 */
    pub static GUID_UNATTEND_SLEEP_TIMEOUT: ::guiddef::GUID; /* winnt.h:13099:1 */
    pub static GUID_USERINTERFACEBUTTON_ACTION: ::guiddef::GUID; /* winnt.h:13209:1 */
    pub static GUID_VIDEO_ADAPTIVE_DISPLAY_BRIGHTNESS: ::guiddef::GUID; /* winnt.h:12995:1 */
    pub static GUID_VIDEO_ADAPTIVE_PERCENT_INCREASE: ::guiddef::GUID; /* winnt.h:12954:1 */
    pub static GUID_VIDEO_ADAPTIVE_POWERDOWN: ::guiddef::GUID; /* winnt.h:12966:1 */
    pub static GUID_VIDEO_ANNOYANCE_TIMEOUT: ::guiddef::GUID; /* winnt.h:12948:1 */
    pub static GUID_VIDEO_CONSOLE_LOCK_TIMEOUT: ::guiddef::GUID; /* winnt.h:13017:1 */
    pub static GUID_VIDEO_CURRENT_MONITOR_BRIGHTNESS: ::guiddef::GUID; /* winnt.h:12988:1 */
    pub static GUID_VIDEO_DIM_TIMEOUT: ::guiddef::GUID; /* winnt.h:12960:1 */
    pub static GUID_VIDEO_FULLSCREEN_PLAYBACK: ::guiddef::GUID; /* winnt.h:13138:1 */
    pub static GUID_VIDEO_POWERDOWN_TIMEOUT: ::guiddef::GUID; /* winnt.h:12942:1 */
    pub static GUID_VIDEO_SUBGROUP: ::guiddef::GUID; /* winnt.h:12936:1 */
    pub static NO_SUBGROUP_GUID: ::guiddef::GUID; /* winnt.h:12825:1 */
    pub static PPM_IDLESTATES_DATA_GUID: ::guiddef::GUID; /* winnt.h:14498:1 */
    pub static PPM_IDLESTATE_CHANGE_GUID: ::guiddef::GUID; /* winnt.h:14490:1 */
    pub static PPM_IDLE_ACCOUNTING_EX_GUID: ::guiddef::GUID; /* winnt.h:14506:1 */
    pub static PPM_IDLE_ACCOUNTING_GUID: ::guiddef::GUID; /* winnt.h:14502:1 */
    pub static PPM_PERFMON_PERFSTATE_GUID: ::guiddef::GUID; /* winnt.h:14514:1 */
    pub static PPM_PERFSTATES_DATA_GUID: ::guiddef::GUID; /* winnt.h:14494:1 */
    pub static PPM_PERFSTATE_CHANGE_GUID: ::guiddef::GUID; /* winnt.h:14482:1 */
    pub static PPM_PERFSTATE_DOMAIN_CHANGE_GUID: ::guiddef::GUID; /* winnt.h:14486:1 */
    pub static PPM_THERMALCONSTRAINT_GUID: ::guiddef::GUID; /* winnt.h:14510:1 */
    pub static PPM_THERMAL_POLICY_CHANGE_GUID: ::guiddef::GUID; /* winnt.h:14518:1 */
}
#[cfg(feature="winapi_desktop")] 
extern "system" {
    pub static CUSTOM_SYSTEM_STATE_CHANGE_EVENT_GUID: ::guiddef::GUID; /* winsvc.h:445:1 */
    pub static DOMAIN_JOIN_GUID: ::guiddef::GUID; /* winsvc.h:366:1 */
    pub static DOMAIN_LEAVE_GUID: ::guiddef::GUID; /* winsvc.h:374:1 */
    pub static FIREWALL_PORT_CLOSE_GUID: ::guiddef::GUID; /* winsvc.h:394:1 */
    pub static FIREWALL_PORT_OPEN_GUID: ::guiddef::GUID; /* winsvc.h:386:1 */
    pub static MACHINE_POLICY_PRESENT_GUID: ::guiddef::GUID; /* winsvc.h:406:1 */
    pub static NAMED_PIPE_EVENT_GUID: ::guiddef::GUID; /* winsvc.h:434:1 */
    pub static NETWORK_MANAGER_FIRST_IP_ADDRESS_ARRIVAL_GUID: ::guiddef::GUID; /* winsvc.h:347:1 */
    pub static NETWORK_MANAGER_LAST_IP_ADDRESS_REMOVAL_GUID: ::guiddef::GUID; /* winsvc.h:355:1 */
    pub static RPC_INTERFACE_EVENT_GUID: ::guiddef::GUID; /* winsvc.h:426:1 */
    pub static USER_POLICY_PRESENT_GUID: ::guiddef::GUID; /* winsvc.h:414:1 */
}
